import { GEARBOXES, LICENCE_CLASSES, WEEKDAYS, options, type Field } from "./fields.js";
import type { Permission } from "./permissions.js";
import { SECTION_TYPE_OPTIONS } from "./sections.js";

export type NavGroup = "School" | "Students" | "Theory" | "Finance" | "Website";

export interface ResourceDef {
  name: string;
  label: string;
  singular: string;
  group: NavGroup | null;
  table: string;
  fields: Field[];
  /** Field used as the item's display name. */
  title: string;
  /** Any one of these lets a user read the resource. */
  view: Permission[];
  edit: Permission;
  /** Manually ordered with a position column. */
  sortable?: boolean;
  sort?: { field: string; direction: "asc" | "desc" };
  search?: string[];
  /** Column the admin filters by when opened from a parent record, e.g. a student's documents. */
  parent?: string;
  /** Records edited through a dedicated screen rather than the generic form. */
  customEditor?: boolean;
}

const published: Field = {
  name: "published",
  label: "Show on website",
  type: "boolean",
  default: true,
  inList: true,
};
const active: Field = {
  name: "active",
  label: "Active",
  type: "boolean",
  default: true,
  inList: true,
};
const branch: Field = {
  name: "branch_id",
  label: "Branch",
  type: "reference",
  resource: "branches",
};

export const DOCUMENT_KINDS = [
  { value: "national_id", label: "National ID" },
  { value: "learners_permit", label: "Learner's permit" },
  { value: "medical_certificate", label: "Medical certificate" },
  { value: "passport_photo", label: "Passport photo" },
  { value: "driving_licence", label: "Driving licence" },
  { value: "other", label: "Other" },
];

export const documentLabel = (kind: string) =>
  DOCUMENT_KINDS.find((option) => option.value === kind)?.label ?? kind;

export const STUDENT_STATUSES = options(
  "enquiry",
  "active",
  "test_ready",
  "passed",
  "on_hold",
  "withdrawn",
);

export const BOOKING_STATUSES = options(
  "requested",
  "confirmed",
  "completed",
  "cancelled",
  "no_show",
);
export const ACTIVE_BOOKING_STATUSES = ["requested", "confirmed"] as const;

export const PAYMENT_METHODS = options(
  "cash",
  "bank_transfer",
  "airtel_money",
  "tnm_mpamba",
  "card",
  "other",
);

const content = (def: Omit<ResourceDef, "group" | "view" | "edit">): ResourceDef => ({
  group: "Website",
  view: ["content.manage"],
  edit: "content.manage",
  ...def,
});

export const RESOURCES: ResourceDef[] = [
  content({
    name: "pages",
    label: "Pages",
    singular: "Page",
    table: "pages",
    title: "title",
    sort: { field: "title", direction: "asc" },
    search: ["title", "slug"],
    customEditor: true,
    fields: [
      { name: "title", label: "Title", type: "text", max: 120, required: true, inList: true },
      {
        name: "slug",
        label: "Web address",
        type: "text",
        max: 80,
        required: true,
        inList: true,
        help: "Lowercase letters, numbers and hyphens, e.g. privacy-policy. Use 'home' for the home page.",
      },
      { name: "seo_title", label: "Search engine title", type: "text", max: 70 },
      { name: "seo_description", label: "Search engine description", type: "textarea", max: 300 },
      { name: "share_image", label: "Image when shared on social media", type: "image" },
      published,
    ],
  }),
  content({
    name: "sections",
    label: "Page sections",
    singular: "Section",
    table: "sections",
    title: "type",
    sortable: true,
    parent: "page_id",
    customEditor: true,
    fields: [
      { name: "page_id", label: "Page", type: "reference", resource: "pages", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: SECTION_TYPE_OPTIONS,
        required: true,
        inList: true,
      },
      { name: "visible", label: "Visible", type: "boolean", default: true, inList: true },
    ],
  }),
  content({
    name: "menu_items",
    label: "Menus",
    singular: "Menu link",
    table: "menu_items",
    title: "label",
    sortable: true,
    fields: [
      { name: "label", label: "Text", type: "text", max: 60, required: true, inList: true },
      { name: "url", label: "Link", type: "url", required: true, inList: true },
      {
        name: "location",
        label: "Where",
        type: "select",
        required: true,
        inList: true,
        options: [
          { value: "header", label: "Top menu" },
          { value: "footer_1", label: "Footer column 1" },
          { value: "footer_2", label: "Footer column 2" },
        ],
      },
      { name: "is_button", label: "Show as a button", type: "boolean" },
      { name: "new_tab", label: "Open in a new tab", type: "boolean" },
      { name: "visible", label: "Visible", type: "boolean", default: true, inList: true },
    ],
  }),
  content({
    name: "posts",
    label: "News & blog",
    singular: "Post",
    table: "posts",
    title: "title",
    sort: { field: "published_on", direction: "desc" },
    search: ["title"],
    fields: [
      { name: "title", label: "Title", type: "text", max: 160, required: true, inList: true },
      { name: "slug", label: "Web address", type: "text", max: 100, required: true },
      {
        name: "category",
        label: "Type",
        type: "select",
        options: options("news", "blog"),
        default: "news",
        inList: true,
      },
      { name: "published_on", label: "Date", type: "date", required: true, inList: true },
      { name: "summary", label: "Summary", type: "textarea", max: 400 },
      { name: "body", label: "Text", type: "markdown", required: true },
      { name: "image", label: "Cover photo", type: "image" },
      { name: "seo_description", label: "Search engine description", type: "textarea", max: 300 },
      published,
    ],
  }),
  content({
    name: "notices",
    label: "Notices",
    singular: "Notice",
    table: "notices",
    title: "title",
    sort: { field: "starts_on", direction: "desc" },
    fields: [
      { name: "title", label: "Title", type: "text", max: 120, required: true, inList: true },
      { name: "message", label: "Message", type: "textarea", max: 400, required: true },
      {
        name: "kind",
        label: "Type",
        type: "select",
        options: options("intake", "holiday", "closure", "general"),
        default: "general",
        inList: true,
      },
      { name: "starts_on", label: "Show from", type: "date", required: true, inList: true },
      { name: "ends_on", label: "Show until", type: "date", inList: true },
      { name: "link_label", label: "Link text", type: "text", max: 60 },
      { name: "link", label: "Link", type: "url" },
      published,
    ],
  }),
  content({
    name: "faqs",
    label: "FAQ",
    singular: "Question",
    table: "faqs",
    title: "question",
    sortable: true,
    search: ["question"],
    fields: [
      { name: "question", label: "Question", type: "text", max: 200, required: true, inList: true },
      { name: "answer", label: "Answer", type: "markdown", max: 4000, required: true },
      { name: "category", label: "Category", type: "text", max: 60, inList: true },
      published,
    ],
  }),
  content({
    name: "testimonials",
    label: "Testimonials",
    singular: "Testimonial",
    table: "testimonials",
    title: "name",
    sortable: true,
    fields: [
      { name: "name", label: "Student name", type: "text", max: 80, required: true, inList: true },
      {
        name: "stars",
        label: "Rating (1–5)",
        type: "number",
        min: 1,
        max: 5,
        default: 5,
        inList: true,
      },
      { name: "quote", label: "Quote", type: "textarea", max: 800, required: true },
      { name: "photo", label: "Photo", type: "image" },
      published,
    ],
  }),
  content({
    name: "gallery",
    label: "Gallery",
    singular: "Photo",
    table: "gallery_items",
    title: "caption",
    sortable: true,
    fields: [
      { name: "image", label: "Photo", type: "image", required: true, inList: true },
      {
        name: "caption",
        label: "Description",
        type: "text",
        max: 160,
        required: true,
        inList: true,
      },
      published,
    ],
  }),
  content({
    name: "downloads",
    label: "Downloads",
    singular: "Download",
    table: "downloads",
    title: "title",
    sortable: true,
    fields: [
      { name: "title", label: "Title", type: "text", max: 120, required: true, inList: true },
      { name: "description", label: "Description", type: "textarea", max: 400 },
      { name: "file", label: "File", type: "file", required: true },
      published,
    ],
  }),
  content({
    name: "branches",
    label: "Branches",
    singular: "Branch",
    table: "branches",
    title: "name",
    sortable: true,
    fields: [
      { name: "name", label: "Name", type: "text", max: 80, required: true, inList: true },
      { name: "address", label: "Address", type: "text", max: 200, required: true, inList: true },
      { name: "phone", label: "Phone", type: "phone" },
      {
        name: "whatsapp_number",
        label: "WhatsApp number (blank uses the main one)",
        type: "phone",
      },
      { name: "hours", label: "Opening hours", type: "text", max: 80 },
      published,
    ],
  }),
  {
    name: "courses",
    label: "Courses & packages",
    singular: "Course",
    group: "School",
    table: "courses",
    title: "name",
    view: ["courses.manage", "students.view", "students.view_own", "finance.view"],
    edit: "courses.manage",
    sortable: true,
    search: ["name"],
    fields: [
      { name: "name", label: "Name", type: "text", max: 120, required: true, inList: true },
      {
        name: "category",
        label: "Type",
        type: "select",
        options: options("course", "refresher", "theory", "addon"),
        default: "course",
        inList: true,
      },
      {
        name: "licence_class",
        label: "Licence class",
        type: "select",
        options: LICENCE_CLASSES,
        inList: true,
      },
      {
        name: "gearbox",
        label: "Gearbox",
        type: "select",
        options: options("manual", "automatic", "either", "not_applicable"),
        default: "either",
      },
      { name: "price", label: "Price", type: "money", required: true, inList: true },
      { name: "lessons", label: "Practical lessons", type: "number", min: 0, max: 500 },
      { name: "lesson_minutes", label: "Minutes per lesson", type: "number", min: 0, max: 480 },
      { name: "theory_sessions", label: "Theory classes", type: "number", min: 0, max: 500 },
      {
        name: "duration",
        label: "Course length (as shown, e.g. 6–10 weeks)",
        type: "text",
        max: 60,
      },
      { name: "summary", label: "Short description", type: "markdown", max: 2000 },
      { name: "included", label: "What's included", type: "tags", max: 20 },
      { name: "min_age", label: "Minimum age", type: "number", min: 0, max: 99 },
      {
        name: "documents_required",
        label: "Documents required",
        type: "multiselect",
        options: DOCUMENT_KINDS,
      },
      {
        name: "requires_permit",
        label: "Learner's permit needed before practical lessons",
        type: "boolean",
      },
      { name: "other_requirements", label: "Other requirements", type: "tags", max: 10 },
      {
        name: "allow_instalments",
        label: "Can be paid in instalments",
        type: "boolean",
        default: true,
      },
      { name: "deposit", label: "Deposit to start", type: "money" },
      { name: "photo", label: "Photo", type: "image" },
      { name: "featured", label: "Highlight as most popular", type: "boolean" },
      published,
    ],
  },
  {
    name: "instructors",
    label: "Instructors",
    singular: "Instructor",
    group: "School",
    table: "instructors",
    title: "name",
    view: [
      "instructors.manage",
      "bookings.view",
      "bookings.view_own",
      "students.view",
      "students.view_own",
    ],
    edit: "instructors.manage",
    sortable: true,
    fields: [
      { name: "name", label: "Name", type: "text", max: 80, required: true, inList: true },
      { name: "role_title", label: "Title shown on website", type: "text", max: 80, inList: true },
      { name: "bio", label: "Short bio", type: "textarea", max: 800 },
      { name: "photo", label: "Photo", type: "image" },
      { name: "phone", label: "Phone", type: "phone" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "licence_classes",
        label: "Teaches licence classes",
        type: "multiselect",
        options: LICENCE_CLASSES,
      },
      { name: "languages", label: "Languages", type: "tags", max: 10 },
      branch,
      {
        name: "availability",
        label: "Weekly availability",
        type: "list",
        max: 21,
        fields: [
          { name: "day", label: "Day", type: "select", options: WEEKDAYS, required: true },
          { name: "start", label: "From", type: "time", required: true },
          { name: "end", label: "To", type: "time", required: true },
        ],
      },
      { name: "user_id", label: "Login account", type: "reference", resource: "staff" },
      {
        name: "show_on_website",
        label: "Show on website",
        type: "boolean",
        default: true,
        inList: true,
      },
      active,
    ],
  },
  {
    name: "vehicles",
    label: "Vehicles",
    singular: "Vehicle",
    group: "School",
    table: "vehicles",
    title: "plate",
    view: ["vehicles.view", "vehicles.manage", "bookings.view", "bookings.manage"],
    edit: "vehicles.manage",
    sort: { field: "plate", direction: "asc" },
    search: ["plate", "make", "model"],
    fields: [
      { name: "plate", label: "Number plate", type: "text", max: 20, required: true, inList: true },
      { name: "make", label: "Make", type: "text", max: 60, required: true, inList: true },
      { name: "model", label: "Model", type: "text", max: 60, required: true, inList: true },
      { name: "year", label: "Year", type: "number", min: 1950, max: 2100 },
      {
        name: "gearbox",
        label: "Gearbox",
        type: "select",
        options: GEARBOXES,
        required: true,
        inList: true,
      },
      {
        name: "licence_classes",
        label: "Used for licence classes",
        type: "multiselect",
        options: LICENCE_CLASSES,
      },
      { name: "dual_controls", label: "Dual controls", type: "boolean", default: true },
      branch,
      { name: "photo", label: "Photo", type: "image" },
      { name: "insurance_expires_on", label: "Insurance expires", type: "date", inList: true },
      { name: "fitness_expires_on", label: "Certificate of fitness expires", type: "date" },
      { name: "last_service_on", label: "Last service", type: "date" },
      { name: "next_service_on", label: "Next service due", type: "date", inList: true },
      { name: "notes", label: "Notes", type: "textarea", max: 2000 },
      active,
    ],
  },
  {
    name: "students",
    label: "Students",
    singular: "Student",
    group: "Students",
    table: "students",
    title: "full_name",
    view: ["students.view", "students.view_own", "finance.view"],
    edit: "students.manage",
    sort: { field: "created_at", direction: "desc" },
    search: ["full_name", "phone", "email", "national_id"],
    customEditor: true,
    fields: [
      {
        name: "full_name",
        label: "Full name",
        type: "text",
        max: 120,
        required: true,
        inList: true,
      },
      { name: "phone", label: "Phone", type: "phone", required: true, inList: true },
      { name: "email", label: "Email", type: "email" },
      { name: "date_of_birth", label: "Date of birth", type: "date" },
      { name: "national_id", label: "National ID number", type: "text", max: 40 },
      { name: "address", label: "Address", type: "textarea", max: 300 },
      { name: "course_id", label: "Course", type: "reference", resource: "courses", inList: true },
      { name: "instructor_id", label: "Instructor", type: "reference", resource: "instructors" },
      branch,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: STUDENT_STATUSES,
        default: "active",
        inList: true,
      },
      { name: "permit_number", label: "Learner's permit number", type: "text", max: 40 },
      { name: "permit_expires_on", label: "Learner's permit expires", type: "date" },
      { name: "emergency_contact", label: "Emergency contact", type: "text", max: 160 },
      { name: "notes", label: "Office notes", type: "textarea", max: 4000 },
    ],
  },
  {
    name: "student_documents",
    label: "Student documents",
    singular: "Document",
    group: null,
    table: "student_documents",
    title: "kind",
    view: ["students.view", "students.view_own"],
    edit: "students.manage",
    parent: "student_id",
    sort: { field: "created_at", direction: "desc" },
    fields: [
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
      },
      {
        name: "kind",
        label: "Document",
        type: "select",
        options: DOCUMENT_KINDS,
        required: true,
        inList: true,
      },
      { name: "file", label: "File", type: "file", required: true },
      { name: "expires_on", label: "Expires", type: "date", inList: true },
      { name: "verified", label: "Checked by office", type: "boolean", inList: true },
    ],
  },
  {
    name: "student_notes",
    label: "Instructor notes",
    singular: "Note",
    group: null,
    table: "student_notes",
    title: "body",
    view: ["students.view", "students.view_own"],
    edit: "students.notes",
    parent: "student_id",
    sort: { field: "created_at", direction: "desc" },
    fields: [
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
      },
      { name: "body", label: "Note", type: "textarea", max: 4000, required: true, inList: true },
      { name: "author_name", label: "Written by", type: "text", readOnly: true, inList: true },
    ],
  },
  {
    name: "skills",
    label: "Skills checklist",
    singular: "Skill",
    group: "School",
    table: "skills",
    title: "name",
    view: ["students.view", "students.view_own", "students.notes", "courses.manage"],
    edit: "courses.manage",
    sortable: true,
    fields: [
      { name: "name", label: "Skill", type: "text", max: 80, required: true, inList: true },
      { name: "category", label: "Group", type: "text", max: 60, inList: true },
      {
        name: "licence_classes",
        label: "Applies to licence classes (blank for all)",
        type: "multiselect",
        options: LICENCE_CLASSES,
      },
      active,
    ],
  },
  {
    name: "bookings",
    label: "Lessons",
    singular: "Lesson",
    group: null,
    table: "bookings",
    title: "starts_at",
    view: ["bookings.view", "bookings.view_own"],
    edit: "bookings.manage",
    sort: { field: "starts_at", direction: "desc" },
    parent: "student_id",
    fields: [
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
        inList: true,
      },
      {
        name: "instructor_id",
        label: "Instructor",
        type: "reference",
        resource: "instructors",
        required: true,
        inList: true,
      },
      { name: "vehicle_id", label: "Vehicle", type: "reference", resource: "vehicles" },
      branch,
      {
        name: "kind",
        label: "Type",
        type: "select",
        options: options("practical", "theory_class", "mock_test"),
        default: "practical",
        inList: true,
      },
      { name: "starts_at", label: "Starts", type: "datetime", required: true, inList: true },
      {
        name: "duration_minutes",
        label: "Length (minutes, blank for the default)",
        type: "number",
        min: 15,
        max: 480,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: BOOKING_STATUSES,
        default: "confirmed",
        inList: true,
      },
      { name: "notes", label: "Booking notes", type: "textarea", max: 1000 },
      { name: "lesson_notes", label: "Instructor's lesson notes", type: "textarea", max: 4000 },
      { name: "ends_at", label: "Ends", type: "datetime", readOnly: true },
    ],
  },
  {
    name: "official_tests",
    label: "Test dates",
    singular: "Test booking",
    group: "Students",
    table: "official_tests",
    title: "scheduled_at",
    view: ["tests.manage", "students.view", "students.view_own"],
    edit: "tests.manage",
    sort: { field: "scheduled_at", direction: "desc" },
    parent: "student_id",
    fields: [
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
        inList: true,
      },
      {
        name: "kind",
        label: "Test",
        type: "select",
        options: options("theory", "road"),
        required: true,
        inList: true,
      },
      {
        name: "scheduled_at",
        label: "Date and time",
        type: "datetime",
        required: true,
        inList: true,
      },
      { name: "location", label: "Test centre", type: "text", max: 120 },
      { name: "licence_class", label: "Licence class", type: "select", options: LICENCE_CLASSES },
      {
        name: "instructor_id",
        label: "Accompanying instructor",
        type: "reference",
        resource: "instructors",
      },
      { name: "vehicle_id", label: "Vehicle", type: "reference", resource: "vehicles" },
      {
        name: "result",
        label: "Result",
        type: "select",
        options: options("booked", "passed", "failed", "absent", "cancelled"),
        default: "booked",
        inList: true,
      },
      { name: "score", label: "Score", type: "text", max: 20 },
      { name: "notes", label: "Notes", type: "textarea", max: 2000 },
    ],
  },
  {
    name: "questions",
    label: "Question bank",
    singular: "Question",
    group: "Theory",
    table: "questions",
    title: "prompt",
    view: ["theory.manage"],
    edit: "theory.manage",
    sort: { field: "created_at", direction: "desc" },
    search: ["prompt", "category"],
    fields: [
      {
        name: "prompt",
        label: "Question",
        type: "textarea",
        max: 600,
        required: true,
        inList: true,
      },
      { name: "image", label: "Picture or road sign", type: "image" },
      { name: "category", label: "Topic", type: "text", max: 60, inList: true },
      {
        name: "choices",
        label: "Answer choices",
        type: "tags",
        max: 6,
        help: "Two to six answers.",
      },
      {
        name: "correct_choice",
        label: "Correct answer (1 = first choice)",
        type: "number",
        min: 1,
        max: 6,
        required: true,
      },
      {
        name: "explanation",
        label: "Explanation shown after answering",
        type: "textarea",
        max: 1000,
      },
      {
        name: "licence_classes",
        label: "Licence classes (blank for all)",
        type: "multiselect",
        options: LICENCE_CLASSES,
      },
      active,
    ],
  },
  {
    name: "theory_tests",
    label: "Practice tests",
    singular: "Test",
    group: "Theory",
    table: "theory_tests",
    title: "name",
    view: ["theory.manage", "theory.results"],
    edit: "theory.manage",
    sortable: true,
    fields: [
      { name: "name", label: "Name", type: "text", max: 120, required: true, inList: true },
      {
        name: "kind",
        label: "Type",
        type: "select",
        options: options("practice", "mock_exam"),
        required: true,
        inList: true,
      },
      {
        name: "question_count",
        label: "Questions per attempt",
        type: "number",
        min: 1,
        max: 200,
        required: true,
        inList: true,
      },
      {
        name: "time_limit_minutes",
        label: "Time limit (minutes, blank for none)",
        type: "number",
        min: 1,
        max: 300,
      },
      {
        name: "pass_mark_percent",
        label: "Pass mark % (blank uses the school default)",
        type: "number",
        min: 1,
        max: 100,
      },
      { name: "categories", label: "Only these topics (blank for all)", type: "tags", max: 20 },
      { name: "licence_class", label: "Licence class", type: "select", options: LICENCE_CLASSES },
      {
        name: "show_answers",
        label: "Show correct answers after submitting",
        type: "boolean",
        default: true,
      },
      active,
    ],
  },
  {
    name: "invoices",
    label: "Invoices",
    singular: "Invoice",
    group: "Finance",
    table: "invoices",
    title: "number",
    view: ["finance.view"],
    edit: "finance.manage",
    sort: { field: "issued_on", direction: "desc" },
    search: ["number"],
    parent: "student_id",
    fields: [
      { name: "number", label: "Number", type: "text", readOnly: true, inList: true },
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
        inList: true,
      },
      { name: "issued_on", label: "Date", type: "date", required: true, inList: true },
      { name: "due_on", label: "Due", type: "date" },
      {
        name: "lines",
        label: "Items",
        type: "list",
        max: 30,
        fields: [
          { name: "description", label: "Description", type: "text", max: 200, required: true },
          {
            name: "quantity",
            label: "Quantity",
            type: "number",
            min: 1,
            max: 1000,
            required: true,
            default: 1,
          },
          { name: "unit_price", label: "Unit price", type: "money", required: true },
        ],
      },
      { name: "discount", label: "Discount", type: "money" },
      {
        name: "instalments",
        label: "Instalment plan",
        type: "list",
        max: 24,
        fields: [
          { name: "due_on", label: "Due", type: "date", required: true },
          { name: "amount", label: "Amount", type: "money", required: true },
        ],
      },
      { name: "notes", label: "Notes", type: "textarea", max: 1000 },
      { name: "total", label: "Total", type: "money", readOnly: true, inList: true },
    ],
  },
  {
    name: "payments",
    label: "Payments",
    singular: "Payment",
    group: "Finance",
    table: "payments",
    title: "receipt_number",
    view: ["finance.view"],
    edit: "finance.manage",
    sort: { field: "paid_on", direction: "desc" },
    search: ["reference", "receipt_number"],
    parent: "student_id",
    fields: [
      { name: "receipt_number", label: "Receipt", type: "text", readOnly: true, inList: true },
      {
        name: "student_id",
        label: "Student",
        type: "reference",
        resource: "students",
        required: true,
        inList: true,
      },
      { name: "invoice_id", label: "Invoice", type: "reference", resource: "invoices" },
      { name: "amount", label: "Amount", type: "money", min: 1, required: true, inList: true },
      {
        name: "method",
        label: "Method",
        type: "select",
        options: PAYMENT_METHODS,
        required: true,
        inList: true,
      },
      { name: "reference", label: "Transaction reference", type: "text", max: 80 },
      { name: "paid_on", label: "Paid on", type: "date", required: true, inList: true },
      { name: "proof", label: "Proof of payment", type: "file" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: options("pending", "confirmed", "rejected"),
        default: "confirmed",
        inList: true,
      },
      { name: "notes", label: "Notes", type: "textarea", max: 1000 },
    ],
  },
  {
    name: "enquiries",
    label: "Enquiries",
    singular: "Enquiry",
    group: "Students",
    table: "enquiries",
    title: "name",
    view: ["enquiries.manage"],
    edit: "enquiries.manage",
    sort: { field: "created_at", direction: "desc" },
    search: ["name", "phone", "email"],
    fields: [
      { name: "name", label: "Name", type: "text", max: 120, required: true, inList: true },
      { name: "phone", label: "Phone", type: "phone", required: true, inList: true },
      { name: "email", label: "Email", type: "email" },
      { name: "course", label: "Course", type: "text", max: 120, inList: true },
      { name: "branch", label: "Branch", type: "text", max: 120 },
      { name: "message", label: "Message", type: "textarea", max: 2000 },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: options("new", "contacted", "enrolled", "closed"),
        default: "new",
        inList: true,
      },
    ],
  },
];

export const RESOURCE_BY_NAME: ReadonlyMap<string, ResourceDef> = new Map(
  RESOURCES.map((r) => [r.name, r]),
);

export function getResource(name: string): ResourceDef | undefined {
  return RESOURCE_BY_NAME.get(name);
}

export const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
